version: "3.7"

# Definição dos Serviços
services:
  # Definição do Serviço do Editor
  n8n_editor:
    image: n8nio/n8n:latest
    command: start
    networks:
      - network_public
    volumes:
    - n8n_data:/data/backup
    environment:
      # Define as configurações do Banco de Dados do Postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      # Configurações do n8n
      - N8N_ENCRYPTION_KEY=${N8N_KEY}
      - N8N_HOST=${DOMINIO_N8N}
      - N8N_EDITOR_BASE_URL=https://${DOMINIO_N8N}/
      - WEBHOOK_URL=https://${WEBHOOK_N8N}/
      - N8N_ENDPOINT_WEBHOOK=webhook
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_LOG_LEVEL=info
      - N8N_METRICS=true
      - N8N_PAYLOAD_SIZE_MAX=16
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=internal
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      # Interface n8n
      - N8N_VERSION_NOTIFICATIONS_ENABLED=true
      - N8N_PUBLIC_API_SWAGGERUI_DISABLED=false
      - N8N_TEMPLATES_ENABLED=true
      - N8N_ONBOARDING_FLOW_DISABLED=true
      - N8N_WORKFLOW_TAGS_DISABLED=false
      - N8N_HIDE_USAGE_PAGE=false
      # Limpeza n8n
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336 # 2 semanas
      - EXECUTIONS_DATA_PRUNE_HARD_DELETE_INTERVAL=15
      - EXECUTIONS_DATA_PRUNE_SOFT_DELETE_INTERVAL=60
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      # Community Nodes e bibliotecas
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=lodash
      - N8N_NODE_PATH=/home/node/.n8n/nodes
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_REINSTALL_MISSING_PACKAGES=true
      # n8n AI
      - N8N_AI_ENABLED=false
      - N8N_AI_PROVIDER=openai
      - N8N_AI_OPENAI_API_KEY=
      #n8n SMTP Email
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=smtp.google.com
      - N8N_SMTP_PORT=25
      - N8N_SMTP_USER=USER
      - N8N_SMTP_PASS=SENHA
      - N8N_SMTP_SENDER=contact@site.com
      - N8N_SMTP_SSL=false
      # Modo fila
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - EXECUTIONS_TIMEOUT=3600
      - EXECUTIONS_TIMEOUT_MAX=7200
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker1
          # - node.labels.app == http # nome do label: app, valor do label: http
      # Limitação
      #resources:
        #limits:
          #cpus: "1"
          #memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.n8n_editor.rule=Host(`${DOMINIO_N8N}`)
        - traefik.http.routers.n8n_editor.entrypoints=websecure
        - traefik.http.routers.n8n_editor.priority=1
        - traefik.http.routers.n8n_editor.tls.certresolver=letsencryptresolver
        - traefik.http.routers.n8n_editor.service=n8n_editor
        - traefik.http.services.n8n_editor.loadbalancer.server.port=5678
        - traefik.http.services.n8n_editor.loadbalancer.passHostHeader=1

  n8n_webhook:
    image: n8nio/n8n:latest
    command: webhook
    networks:
      - network_public
    environment:
      # Define as configurações do Banco de Dados do Postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      # Configurações do n8n
      - N8N_ENCRYPTION_KEY=${N8N_KEY}
      - N8N_HOST=${DOMINIO_N8N}
      - N8N_EDITOR_BASE_URL=https://${DOMINIO_N8N}/
      - WEBHOOK_URL=https://${WEBHOOK_N8N}/
      - N8N_ENDPOINT_WEBHOOK=webhook
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_LOG_LEVEL=info
      - N8N_METRICS=true
      - N8N_PAYLOAD_SIZE_MAX=16
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=internal
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      # Interface n8n
      - N8N_VERSION_NOTIFICATIONS_ENABLED=true
      - N8N_PUBLIC_API_SWAGGERUI_DISABLED=false
      - N8N_TEMPLATES_ENABLED=true
      - N8N_ONBOARDING_FLOW_DISABLED=true
      - N8N_WORKFLOW_TAGS_DISABLED=false
      - N8N_HIDE_USAGE_PAGE=false
      # Limpeza n8n
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336 # 2 semanas
      - EXECUTIONS_DATA_PRUNE_HARD_DELETE_INTERVAL=15
      - EXECUTIONS_DATA_PRUNE_SOFT_DELETE_INTERVAL=60
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      # Community Nodes e bibliotecas
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=lodash
      - N8N_NODE_PATH=/home/node/.n8n/nodes
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_REINSTALL_MISSING_PACKAGES=true
      # n8n AI
      - N8N_AI_ENABLED=false
      - N8N_AI_PROVIDER=openai
      - N8N_AI_OPENAI_API_KEY=
      #n8n SMTP Email
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=smtp.google.com
      - N8N_SMTP_PORT=25
      - N8N_SMTP_USER=USER
      - N8N_SMTP_PASS=SENHA
      - N8N_SMTP_SENDER=contact@site.com
      - N8N_SMTP_SSL=false
      # Modo fila
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - EXECUTIONS_TIMEOUT=3600
      - EXECUTIONS_TIMEOUT_MAX=7200
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker1
          # - node.labels.app == workers # nome do label: app, valor do label: workers
      #resources:
        #limits:
          #cpus: "1"
          #memory: 1024M
      labels:
        # Configura o Roteamento do Traefik
        - traefik.enable=true
        - traefik.http.routers.n8n_webhook.rule=(Host(`${WEBHOOK_N8N}`))
        - traefik.http.routers.n8n_webhook.entrypoints=websecure
        - traefik.http.routers.n8n_webhook.priority=1
        - traefik.http.routers.n8n_webhook.tls.certresolver=letsencryptresolver
        - traefik.http.routers.n8n_webhook.service=n8n_webhook
        - traefik.http.services.n8n_webhook.loadbalancer.server.port=5678
        - traefik.http.services.n8n_webhook.loadbalancer.passHostHeader=1

  n8n_worker:
    image: n8nio/n8n:latest
    command: worker --concurrency=10
    networks:
      - network_public
    environment:
      # Define as configurações do Banco de Dados do Postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      # Configurações do n8n
      - N8N_ENCRYPTION_KEY=${N8N_KEY}
      - N8N_HOST=${DOMINIO_N8N}
      - N8N_EDITOR_BASE_URL=https://${DOMINIO_N8N}/
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=internal
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      # Community Nodes
      - N8N_NODE_PATH=/home/node/.n8n/nodes
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - WEBHOOK_URL=https://${WEBHOOK_N8N}/
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336 # 2 semanas
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker1
          # - node.labels.app == webhooks # nome do label: app, valor do label: webhooks
      #resources:
        #limits:
          #cpus: "1"
          #memory: 1024M

volumes:
  n8n_data:
    external: true
    name: n8n_data

networks:
  network_public:
    name: network_public
    external: true
