version: '3.7'
services:
    redis:
        image: redis:latest
        command: [
            "redis-server",
            "--appendonly",
            "yes",
            "--port",
            "6379"
        ]
        networks:
            - network_public
        volumes:
            - redis_data:/data
        deploy:
            placement:
                constraints: [node.role == manager]
            #resources:
                #limits:
                    #cpus: "1"
                    #memory: 1024M
volumes:
  redis_data:
    external: true
    name: redis_data

networks:
  network_public:
    external: true
    name: network_public
